// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class SubscriptionPlan
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public decimal Price { get; set; }

    public int MaxUsers { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Tenant> Tenants { get; set; } = new List<Tenant>();
}