// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class User : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public bool IsActive { get; set; }
    public bool IsVerified { get; set; } 

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Tenant Tenant { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}